In [1]:
import numpy as np

In [3]:
# create np.array from python list
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
# create np.array from python list.
# if types don't much - numpy will upcast if possible
np.array([1, 4.2, 2, 5 , 3])

array([1. , 4.2, 2. , 5. , 3. ])

In [6]:
# explicitely set the data type
np.array([1, 2.3, 4.3, 5.1], dtype="float")

array([1. , 2.3, 4.3, 5.1])

In [11]:
# multidimentional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Creating arrays from scratch

In [12]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# create a 3x5 floating point array with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# create a 3x5 floating point array with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# create array filled with linnear sequence starting from 0 to 20 with step 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# create array of five values evenly spaced between 0 and 1
np.linspace(0, 1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.49690592, 0.24490857, 0.67552423],
       [0.58899581, 0.12532041, 0.38744623],
       [0.87972224, 0.25088699, 0.58928405]])

In [18]:
# create 3x3 array of normally distributed random values with mean 0 and standart deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.61916675, -0.05323279,  1.40022983],
       [-1.04765717, -1.82183178,  0.62503471],
       [ 0.66299583, -0.32761055,  0.80171601]])

In [19]:
# create 3x3 array of random integers in the interval [0, 10]
np.random.randint(0, 10, (3, 3))

array([[4, 2, 8],
       [7, 3, 5],
       [6, 6, 1]])

In [20]:
# create 3x3 identity matrix
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays

In [29]:
np.random.seed(73)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array)

In [31]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [32]:
x3.dtype

dtype('int32')

Other attributes include itemsize, which lists the size (in bytes) of each array element, and nbytes, which lists the total size (in bytes) of the array

In [34]:
print("itemsize:", x3.itemsize, " bytes")
print("nbytes:", x3.nbytes, " bytes")

itemsize: 4  bytes
nbytes: 240  bytes


### Indexing of arrays: Getting and setting the value of individual array elements

In [35]:
x1

array([6, 2, 0, 8, 3, 1])

In [36]:
x1[0]

6

In [37]:
x1[-1]

1

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices

In [38]:
x2

array([[6, 7, 1, 4],
       [5, 7, 7, 4],
       [9, 5, 3, 2]])

In [39]:
x2[0, 0]

6

In [40]:
x2[2, -1]

2

In [41]:
x2[0, 0] = 12

In [42]:
x2

array([[12,  7,  1,  4],
       [ 5,  7,  7,  4],
       [ 9,  5,  3,  2]])

In [43]:
x1

array([6, 2, 0, 8, 3, 1])

In [44]:
x1[0] = 3.14159    # this will be truncated to 3

In [45]:
x1

array([3, 2, 0, 8, 3, 1])

Slicing of arrays: Getting and setting smaller subarrays within a larger array

NumPy slicing syntax follows that of the standard Python list - x\[start:stop:step\]

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[:5]    # first five elements

array([0, 1, 2, 3, 4])

In [49]:
x[5:]    # elements after index 5

array([5, 6, 7, 8, 9])

In [50]:
x[4:7]    # middle sub-array

array([4, 5, 6])

In [53]:
x[::2]    # every other element

array([0, 2, 4, 6, 8])

In [55]:
x[1::2]   # every other element starting from index 1

array([1, 3, 5, 7, 9])

In [56]:
x[::-1]   # all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [57]:
x[5::-2]    # reversed every other from index 5

array([5, 3, 1])

In [58]:
x2

array([[12,  7,  1,  4],
       [ 5,  7,  7,  4],
       [ 9,  5,  3,  2]])

In [60]:
x2[:2, :3]   # two rows three columns

array([[12,  7,  1],
       [ 5,  7,  7]])

In [62]:
x2[:, ::2]   # all rows every other column

array([[12,  1],
       [ 5,  7],
       [ 9,  3]])

In [64]:
x2[::-1, ::-1]   # subarray dimensions reversed together

array([[ 2,  3,  5,  9],
       [ 4,  7,  7,  5],
       [ 4,  1,  7, 12]])

In [65]:
print(x2[:, 0])    # all rows first column

[12  5  9]


In [66]:
print(x2[0, :])    # first row all columns

[12  7  1  4]


In [67]:
print(x2[0])    # first row all columns

[12  7  1  4]


array slices return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies

In [68]:
print(x2)

[[12  7  1  4]
 [ 5  7  7  4]
 [ 9  5  3  2]]


In [69]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  7]
 [ 5  7]]


In [70]:
x2_sub[0, 0] = 99

In [71]:
print(x2)

[[99  7  1  4]
 [ 5  7  7  4]
 [ 9  5  3  2]]


Creating copies of arrays

In [73]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  7]
 [ 5  7]]


In [75]:
x2_sub_copy[0, 0] = 73
print(x2_sub_copy)
print(x2)

[[73  7]
 [ 5  7]]
[[99  7  1  4]
 [ 5  7  7  4]
 [ 9  5  3  2]]


### Reshaping of arrays: Changing the shape of a given array

In [79]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
x = np.array([1, 2, 3])

In [85]:
x.reshape((1, 3))   # row vector via reshape

array([[1, 2, 3]])

In [86]:
x[np.newaxis, :]   # row vector via newaxis

array([[1, 2, 3]])

In [87]:
x.reshape((3, 1))   # column vector via reshape

array([[1],
       [2],
       [3]])

In [88]:
x[:, np.newaxis]   # column vector via newaxis

array([[1],
       [2],
       [3]])

### Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [89]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [90]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [91]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [96]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [98]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [99]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit

In [100]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [101]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [103]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
