In [1]:
import numpy as np

In [2]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [4]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [5]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [ ]:
# +	np.add	Addition (e.g., 1 + 1 = 2)
# -	np.subtract	Subtraction (e.g., 3 - 2 = 1)
# -	np.negative	Unary negation (e.g., -2)
# *	np.multiply	Multiplication (e.g., 2 * 3 = 6)
# /	np.divide	Division (e.g., 3 / 2 = 1.5)
# //	np.floor_divide	Floor division (e.g., 3 // 2 = 1)
# **	np.power	Exponentiation (e.g., 2 ** 3 = 8)
# %	np.mod	Modulus/remainder (e.g., 9 % 4 = 1)

In [7]:
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)
np.abs(x)

array([2, 1, 0, 1, 2])

array([2, 1, 0, 1, 2])

### Trigonometric functions

In [8]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [9]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [10]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [17]:
# exponentials
x = [0.69314718, 1.38629436, 2.30258509]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [0.69314718, 1.38629436, 2.30258509]
e^x   = [2.         4.         9.99999997]
2^x   = [1.61680667 2.61406381 4.93340966]
3^x   = [ 2.14148606  4.58596256 12.54909154]


In [18]:
# inverse of the exponentials - the logarithms
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


specialized versions that are useful for maintaining precision with very small input. When x is very small, these functions give more precise values than if the raw np.log or np.exp were to be used.

In [19]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


#### Specifying output

In [20]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

array([ 0., 10., 20., 30., 40.])

[ 0. 10. 20. 30. 40.]


### Aggregates

In [21]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [22]:
np.multiply.reduce(x)

120

In [23]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [24]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

### Outer product

In [25]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])