In [1]:
import numpy as np

| Operator 	| Equivalent       	|
|----------	|------------------	|
| ==       	| np.equal         	|
| <        	| np.less          	|
| >        	| np.greater       	|
| !=       	| np.not_equal     	|
| <=       	| np.less_equal    	|
| >=       	| np.greater_equal 	|

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x < 3  # less than

array([ True,  True, False, False, False])

In [4]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [5]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [6]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [7]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [8]:
x == 3  # equal

array([False, False,  True, False, False])

In [9]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [10]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [11]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [12]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [18]:
np.sum(x < 6)

8

In [19]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [20]:
# are there any values greater than 8?
np.any(x > 8)

True

In [21]:
# are there any values less than zero?
np.any(x < 0)

False

In [22]:
# are all values less than 10?
np.all(x < 10)

True

In [23]:
# are all values equal to 6?
np.all(x == 6)

False

In [24]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [26]:
np.sum((x > 5) & (x < 10))

4

| Operator 	| Equivalent ufunc 	|
|----------	|------------------	|
| &        	| np.bitwise_and   	|
| ^        	| np.bitwise_xor   	|
| \|       	| np.bitwise_or    	|
| ~        	| np.bitwise_not   	|

### Boolean Arrays as Masks

In [28]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [29]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [30]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [31]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

In [32]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [33]:
(x > 4) and (x < 8)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()